#Group 5 

```{r}
#Section 1.0
#import necessary libraries 
library(dplyr)
library(ggplot2)
library(leaflet)
library(igraph)
library(mapview)
```

```{r}
#Section 1.1 - only necessary to run if new txt file is retrieved from BAST website

#Reformat data downloaded from BAST to isolate A level roads in June 
df_all<- read.table("2013_A_S.txt", sep = ";", header=TRUE)

#Filter by land (column 9 for bayern)
df_A_2013 <- df_all %>% filter(Land %in% c(9))


#Filter by region 
#df_A_2013 <- df_A_2013 %>% filter((TKNR >2520 & TKNR < 2528) | (TKNR >2620 & TKNR < 2628))

```

```{r}
#Section 1.2 - only necessary to run if new txt file is retrieved from BAST website

#Reformat data downloaded from BAST to isolate B level roads in June 
df_all_B<- read.table("2013_B_S.txt", sep = ";", header=TRUE)

#Filter by land (column 9 for bayern)
df_B_2013 <- df_all_B %>% filter(Land %in% c(9))

#Filter by Date
df_date_range_B <- df_B_2013 %>% filter(Datum>130531 & Datum<130701 )
#write June data to csv
write.csv(df_date_range_B, file = "dataB_2013_BH_June.csv")


```



```{r}
#Section 2.0 - create dataframe with A(BH) and B(BB) level road data

df_BH <- read.csv("input/dataA_2013_BH_June.csv")
df_BB <-  read.csv("input/dataB_2013_BH_June.csv")
```



```{r}
#Section 3.0 - Option to plot traffic in both directions at specific counting station 

df_BH_zst1 <-  df_BH %>% filter((Zst == 9171 ))


#plot of all reverse and forward counts at selected station in June
ggplot(df_BH_zst1, aes(x=Stunde, y = KFZ_R1)) +   #plot forward direction
  geom_line(aes(color = "R1")) + 
  geom_line(aes(y=KFZ_R2, color = "R2")) +       #plot reverse direction
  facet_wrap(~Zst) + ylab("cars per hour") + theme_bw()  #group by ZST(counting station ID)


```


```{r}
#Section 4.0 -Rearrange data to report daily total counts for each day of the month 

#For all data points with the same station, date, weekday
#Sum hourly values to daily values 
#for Autobahn
df_daily_A <- df_BH %>% group_by( Zst, Datum, Wotag)%>% 
  summarise(SUM_KFZ_R1 = sum(KFZ_R1, na.rm = TRUE), SUM_KFZ_R2 = sum(KFZ_R2, na.rm = TRUE))

#for bundestrasse
df_daily_B <- df_BB %>% group_by( Zst, Datum, Wotag)%>% 
  summarise(SUM_KFZ_R1 = sum(KFZ_R1, na.rm = TRUE), SUM_KFZ_R2 = sum(KFZ_R2, na.rm = TRUE))


```


```{r}
#Section 4.1 - Establish new index based on number of days in the month of June 
 
#create new column to assign dates a number (1-31)
alldates <- sort(unique(df_daily_A$Datum)) 
alldates_values <- seq(1:length(alldates))
names(alldates_values) <- alldates

#add new index column to df
df_daily_A <- df_daily_A %>% mutate(day = alldates_values[as.character(Datum)]) 
df_daily_B <- df_daily_B %>% mutate(day = alldates_values[as.character(Datum)]) 

```

```{r}
#Section 5.0 - Option to plot traffic flow at specific A level station and specific B level station to compare

#Filter by station to observe plot - select A level station 
df_daily_zst_A <- df_daily_A %>% filter((Zst == 9028 ))
#9295 B
#9023 A
                                  
#plot for A
ggplot(df_daily_zst_A, aes(x = day)) +
  geom_line(aes(y=SUM_KFZ_R1, color = "R1")) +
  geom_line(aes(y=SUM_KFZ_R2, color = "R2")) + 
  facet_wrap(~Zst) + theme_bw()

#Filter by station to observe plot - select B level station 
df_daily_zst_B <- df_daily_B %>% filter((Zst == 9320 ))  

#plot for B
ggplot(df_daily_zst_B, aes(x = day)) +
  geom_line(aes(y=SUM_KFZ_R1, color = "R1")) +
  geom_line(aes(y=SUM_KFZ_R2, color = "R2")) + 
  facet_wrap(~Zst) + theme_bw()

```


```{r}
#Section 6.0 - Determine mean traffic flow at each counting station over the month of June and calculate the relative difference 

#filter data to from groups with same counter device and weekday
#use mutate function to add column with mean of sum KZR1, KZR2
#use mutate again to add column for difference between mean and KZR1 value

df_mean_A <- df_daily_A %>%  group_by( Zst, Wotag) %>% 
  mutate(MEAN_KFZ_R1 = mean(SUM_KFZ_R1, na.rm = TRUE), MEAN_KFZ_R2 = mean(SUM_KFZ_R2, na.rm = TRUE)) %>% 
  mutate(DIFF_R1 = 100*(SUM_KFZ_R1-MEAN_KFZ_R1)/MEAN_KFZ_R1, DIFF_R2 = 100*(SUM_KFZ_R2-MEAN_KFZ_R2)/MEAN_KFZ_R2)

df_mean_B <- df_daily_B %>%  group_by( Zst, Wotag) %>% 
  mutate(MEAN_KFZ_R1 = mean(SUM_KFZ_R1, na.rm = TRUE), MEAN_KFZ_R2 = mean(SUM_KFZ_R2, na.rm = TRUE)) %>% 
  mutate(DIFF_R1 = 100*(SUM_KFZ_R1-MEAN_KFZ_R1)/MEAN_KFZ_R1, DIFF_R2 = 100*(SUM_KFZ_R2-MEAN_KFZ_R2)/MEAN_KFZ_R2)


```


```{r}
#Section 6.1 - Find stations with noteworthy deviations

#identify columns where relative diff is below 50% - create new dataframes to store these values 
df_dev_A <- df_mean_A %>% filter(DIFF_R1 < -50 | DIFF_R2 < -50 )
df_dev_B <- df_mean_B %>% filter(DIFF_R1 < -50 | DIFF_R2 < -50 )

# #identify days with normal traffic patterns
# df_dev_low_A <- df_mean_A %>% filter(DIFF_R1 == 0 | DIFF_R2 ==0 )
# df_dev_low_B <- df_mean_B %>% filter(DIFF_R1 < -1 | DIFF_R2 < -1 )

#create DF for plotting deviations at identified stations for entire month (not just when largest deviation occurs)
df_plot_dev_A <- df_mean_A %>% filter(DIFF_R1 | DIFF_R2 )%>% filter((Zst == 9026 ))
df_plot_dev_B <- df_mean_B %>% filter(DIFF_R1 | DIFF_R2 )%>% filter((Zst == 9320 ))

#plot deviations at different stations
#A level roads
ggplot(df_plot_dev_A, aes(x=day)) + geom_line(aes(y=DIFF_R1, color = "R1")) +geom_line(aes(y=DIFF_R2, color = "R2")) + facet_wrap(~Zst) + xlim(1,10) + theme_bw()

#B level roads
ggplot(df_plot_dev_B, aes(x=day)) + geom_line(aes(y=DIFF_R1, color = "R1")) +geom_line(aes(y=DIFF_R2, color = "R2")) + facet_wrap(~Zst) + xlim(1,10) + theme_bw()

```

```{r}
#Section 6.2 - Optional section to plot mean at specific station 

df_mean_one_zst <- df_mean_A %>% filter((Zst == 9023 ))

#plot relative difference 
ggplot(df_mean_one_zst, aes(x=day)) + geom_line(aes(y=DIFF_R1, color = "R1")) +geom_line(aes(y=DIFF_R2, color = "R2")) + facet_wrap(~Zst) + theme_bw()

```


```{r}
#Section 7.0 - Create a map with the A level(red) and B(blue) level stations marked 

library(leaflet)

#read in long/lat for counting stations from file
#convert WGS84 coordinates to Lon, Lat values using as(numberic....)
df_lonlats <- read.table("input/Jawe2013.csv", sep = ";", header=TRUE) %>% 
  mutate(lat = as.numeric(gsub(",",".",Koor_WGS84_N)), 
         lon =  as.numeric(gsub(",",".",Koor_WGS84_E)))

selected_Zst <- unique(df_mean_A$Zst)
Zst_lonlats_A <- df_lonlats %>% filter(DZ_Nr %in% selected_Zst)
selected_Zst_B <- unique(df_mean_B$Zst)
Zst_lonlats_B <- df_lonlats %>% filter(DZ_Nr %in% selected_Zst_B)

#Add autbahn and Bundestrasse markers to map 

map_A <- leaflet(Zst_lonlats_A) %>% addTiles() %>% 
  addCircleMarkers(lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red")

map_A <-  addCircleMarkers(map_A, data =Zst_lonlats_B, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "blue")


```


```{r}
#Section 7.1 - add graph network to the map 

#Add our network to map with stations marked in blue and red

arcs <- read.csv("input/Arcs_Flooding.csv")
nodes <- read.csv("input/Nodes_Flooding.csv")

#create map with nodes
m_org <- leaflet(nodes) %>% addTiles() %>% addCircleMarkers(lat = ~LAT ,lng = ~LON, weight = 1, opacity = 1, radius = 3, label = ~as.character(DZ_Nr))


#add arcs(edges)
for(i in 1:nrow(arcs)){
  node_ids <- c(arcs$SOURCE_ID[i], arcs$TARGET_ID[i])
  df_pol <- nodes %>% filter(DZ_Nr %in% node_ids)
  m_org <- addPolylines(m_org, data = df_pol, lng = ~LON, lat = ~LAT, opacity = 0.9, group = "mylines", weight = 2) #, stroke = F)
}


#add station markers for A level roads
m_org <- addCircleMarkers(m_org, data = Zst_lonlats_A, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

#add station markers for B level roads
m_org <- addCircleMarkers(m_org, data =Zst_lonlats_B, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "blue")
```


```{r}
#Section 7.2 - Optional additon for marking stations of interest (for presentation only)

#marker for 9026
 m_org <- addCircleMarkers(m_org, data =Zst_lonlats_A, lat = 47.80351657 ,lng = 12.301066 ,label = ~as.character(DZ_Nr), color = "darkorange")
# 
# # marker for 9147
#  m_org <- addCircleMarkers(m_org, data =Zst_lonlats_B, lat = 47.71463128 ,lng = 12.47605042 ,label = ~as.character(DZ_Nr), color = "darkorange")
#  
#  # marker for 9023
#  m_org <- addCircleMarkers(m_org, data =Zst_lonlats_A, lat = 47.80598654 ,lng = 12.13809192 ,label = ~as.character(DZ_Nr), color = "darkorange")
# 
# # marker for 9121
#  m_org <- addCircleMarkers(m_org, data =Zst_lonlats_B, lat = 47.69261768 ,lng = 12.84981641 ,label = ~as.character(DZ_Nr), color = "deepskyblue")
# 
# # marker for 9285
#  m_org <- addCircleMarkers(m_org, data =Zst_lonlats_B, lat = 47.67129144 ,lng = 12.76316727 ,label = ~as.character(DZ_Nr), color = "deepskyblue")
 
 # marker for 9028
 m_org <- addCircleMarkers(m_org, data =Zst_lonlats_A, lat = 47.83238379 ,lng = 12.38918719 ,label = ~as.character(DZ_Nr), color = "darkorange")
 # 
 # # marker for 9109
 # m_org <- addCircleMarkers(m_org, data =Zst_lonlats_B, lat = 47.92615692 ,lng = 12.93863496 ,label = ~as.character(DZ_Nr), color = "darkorange")
```


```{r}
#Section 7.3 - Plot original map and save it 

#show map of original network graph (all arcs and nodes included)
m_org

#create HTML to display map 
mapshot(m_org,url = paste0(getwd(), "/map.html"))

```

```{r}
#Section 7.4 - Plot original network graph without map

#create network graph from arc and nodes
graph_BH <- graph_from_data_frame(d = arcs[,2:3], vertices = nodes, directed = FALSE)

lo <- as.matrix(nodes[,c("LON","LAT")])

plot(graph_BH, vertex.size = 3, layout=lo, vertex.label = NA)

```

```{r}
#Section 8.0 - Centrality Measures of Original Network (all nodes/arcs in place)

#Color Legend for Centrality Plots

colfunc <- colorRampPalette(c("blue","green",'yellow','red'))
colfunc(100)
plot(rep(1,100),col=colfunc(100),  pch=19,cex=3)

#blue = 0 lowest value, red = highest  value 
pal = colorRampPalette(c("blue","green",'yellow','red'))

```



```{r}
#Section 8.1 - Betweeness Centrality 

#blue = 0 betweenes value, red = highest betweeness value 
pal = colorRampPalette(c("blue","green",'yellow','red'))

#Use centr_betw function to determine betweeness centrality of our graph and save in DF
between_vals <- centr_betw(graph_BH, directed = FALSE)$res
graphCol_bet = pal(100)[as.numeric(cut(between_vals,breaks = 100))]

#plot network with nodes colored based on betweeness value 
plot(graph_BH, vertex.color=graphCol_bet, vertex.size = 5, vertex.label = NA, layout=lo)


```

```{r}
#Section 8.2 - Eigenvector Centrality original map 

#determine eigen values of nodes in our graph 
eigen_vals <- centr_eigen(graph_BH)$vector
graphCol_bet = pal(100)[as.numeric(cut(eigen_vals,breaks = 100))]

#plot network with nodes colored based on eigen value 
plot(graph_BH, vertex.color=graphCol_bet, vertex.size = 5, vertex.label = NA, layout=lo)

```

```{r}
#Section 8.3 - Closeness Centrality original map 
 
#determine closeness values of nodes in our graph 
close_vals  <- centr_clo(graph_BH)$res

close_vals_opt2 <- closeness(
                              graph_BH,
                              vids = V(graph_BH),
                              mode = c("all"),
                              weights = arcs$ARC_LENGTH,
                              normalized = TRUE,
                              cutoff = -1
                            )
close_vals_opt3 <- harmonic_centrality(
                        graph_BH,
                        vids = V(graph_BH),
                        mode = c( "all"),
                        weights = arcs$ARC_LENGTH,
                        normalized = FALSE,
                        cutoff = -1
                      )

graphCol_bet = pal(100)[as.numeric(cut(close_vals,breaks = 100))]
graphCol_bet_opt2 = pal(100)[as.numeric(cut(close_vals_opt2,breaks = 100))]
graphCol_bet_opt3 = pal(100)[as.numeric(cut(close_vals_opt3,breaks = 100))]

#plot network with nodes colored based on closeness value 
plot(graph_BH, vertex.color=graphCol_bet, vertex.size = 5, vertex.label = NA, layout=lo)
plot(graph_BH, vertex.color=graphCol_bet_opt2, vertex.size = 5, vertex.label = NA, layout=lo)
plot(graph_BH, vertex.color=graphCol_bet_opt3, vertex.size = 5, vertex.label = NA, layout=lo)

```

```{r}
#Section 8.4 - Degree Centrality original map 

#determine degree values of nodes in our graph 
deg_vals  <- vals_deg <- centr_degree(graph_BH)$res

graphCol_bet = pal(100)[as.numeric(cut(deg_vals,breaks = 100))]

#plot network with nodes colored based on closeness value 
plot(graph_BH, vertex.color=graphCol_bet, vertex.size = 5, vertex.label = NA, layout=lo)



```

```{r}
#Section 9.0 - Create new graph with arcs removed at points where largest deviations occurred and display it on a map 

#Remove paths where large deviations occurred (9028 & 9026)
#Read in new csv where identified nodes are removed from arcs csv, nodes file is renamed but unchanged 
arcs_dev <- read.csv("input/Arcs_Flooding_removed_9028_9026.csv")
nodes_dev <- read.csv("input/Nodes_Flooding.csv")

#create map with nodes
m_dev <- leaflet(nodes_dev) %>% addTiles() %>% addCircleMarkers(lat = ~LAT ,lng = ~LON, weight = 1, opacity = 1, radius = 3, label = ~as.character(DZ_Nr))


#add arcs(edges)
for(i in 1:nrow(arcs_dev)){
  node_ids <- c(arcs_dev$SOURCE_ID[i], arcs_dev$TARGET_ID[i])
  df_pol <- nodes_dev %>% filter(DZ_Nr %in% node_ids)
  m_dev <- addPolylines(m_dev, data = df_pol, lng = ~LON, lat = ~LAT, opacity = 0.9, group = "mylines", weight = 2) #, stroke = F)
}

#show graph 
m_dev


#add station markers A level roads 
m_dev <- addCircleMarkers(m_dev, data = Zst_lonlats_A, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

#add station markers B level roads 
m_dev <- addCircleMarkers(m_dev, data =Zst_lonlats_B, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "blue") 

#show map
m_dev

```

```{r}
#create HTML to display map
mapshot(m_dev,url = paste0(getwd(), "/map_dev.html"))

```


```{r}
#Section 9.1 - isolate network graph from map 

#create network graph from arc and nodes with deviation removed 
graph_BH_dev <- graph_from_data_frame(d = arcs_dev[,2:3], vertices = nodes_dev, directed = FALSE)

lo <- as.matrix(nodes_dev[,c("LON","LAT")])


plot(graph_BH_dev, vertex.size = 3, layout=lo, vertex.label = NA)


```


```{r}
#Section 10.0  - Betweeness Centrality with deviation removed 

#Ensure correct deviation graph is used 
graph_BH_dev <- graph_from_data_frame(d = arcs_dev[,2:3], vertices = nodes_dev, directed = FALSE)

#blue = 0 betweenes value, red = highest betweeness value 
pal = colorRampPalette(c("blue","green",'yellow','red'))

#Use centr_betw function to determine betweeness centrality of our graph and save in DF
between_vals_dev <- centr_betw(graph_BH_dev, directed = FALSE)$res

graphCol_bet = pal(100)[as.numeric(cut(between_vals_dev,breaks = 100))]

#plot network with nodes colored based on betweeness value 
plot(graph_BH_dev, vertex.color=graphCol_bet, vertex.size = 5, vertex.label = NA, layout=lo)

```


```{r}

#Section 10.1 - Compare betweeness centrality before and after deviation removed 

#calculate relative diff between original and modified graph 
#if betweeness value org > 0 then relative diff = rel change calc
#else rel diff = 0
rel_change <- ifelse(between_vals > 0, (between_vals_dev - between_vals)/between_vals, 0)

#plot igraph:
#use 3 colors: red - decrease, white - no change, blue - increase
graphCol_dev = rep("white",length(rel_change))
nodes_dev <- nodes %>% mutate(rel_change = rel_change, bet= between_vals, betdev = between_vals_dev) %>% mutate(rel_color = ifelse(rel_change==0, "White", ifelse(rel_change<0, "red", "blue")))

#show which nodes changed on graph 
plot(graph_BH_dev, vertex.color=nodes_dev$rel_color, vertex.size = 5, vertex.label = NA, layout=lo)

```

```{r}
#Section 10.2 - plot relative diff of betweeness centrality on leaflet map

# color scheme:where white  = no change, red = decrease, blue = increase 
minVal <- abs(min(rel_change))
maxVal <- abs(max(rel_change))
rc1 <- colorRampPalette(colors = c("white", "blue"), space = "Lab")(maxVal*10)
rc2 <- colorRampPalette(colors = c("red", "white"), space = "Lab")(minVal*10)
rampcols <- c(rc2, rc1)
col_pal <- colorNumeric(palette = rampcols, domain =rel_change)


m2 <- leaflet(nodes_dev) %>% addTiles() 

for(i in 1:nrow(arcs_dev)){
  node_ids <- c(arcs_dev$SOURCE_ID[i], arcs_dev$TARGET_ID[i])
  df_pol <- nodes %>% filter(DZ_Nr %in% node_ids)
  m2 <- addPolylines(m2, data = df_pol, lng = ~LON, lat = ~LAT, opacity = 0.9, group = "mylines", weight = 2) 
}
m2 <- addCircleMarkers(m2, lat = ~LAT ,lng = ~LON, weight = 1, opacity = 1, radius = 5,fillOpacity = 1, fillColor = ~col_pal(rel_change), label = ~as.character(rel_change)) %>% addLegend(position = "bottomleft", pal = col_pal, values = ~rel_change, title = as.character("Dev"),opacity = 1) 


m2 <- addCircleMarkers(m2, data = Zst_lonlats_A, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

m2 <- addCircleMarkers(m2, data = Zst_lonlats_B, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

m2

```

```{r}
#Section 10.3
#create HTML to display map 
mapshot(m2,url = paste0(getwd(), "/map_rel_diff_betw.html"))

```

```{r}
#Section 11.0 - Eigenvector Centrality with deviation removed 

#Ensure correct deviation graph is used 
graph_BH_dev <- graph_from_data_frame(d = arcs_dev[,2:3], vertices = nodes_dev, directed = FALSE)

#blue = 0 betweenes value, red = highest betweeness value 
pal = colorRampPalette(c("blue","green",'yellow','red'))

eigen_vals_dev <- centr_eigen(graph_BH_dev)$vector

graphCol_bet = pal(100)[as.numeric(cut(eigen_vals_dev,breaks = 100))]

plot(graph_BH_dev, vertex.color=graphCol_bet, vertex.size = 5, vertex.label = NA, layout=lo)


```

```{r}
#Section 11.1 - Compare eigen vector centrality before and after deviation removed 

#calculate relative diff between original and modified graph 
#if betweeness value org > 0 then relative diff = rel change calc
#else rel diff = 0
rel_change <- ifelse(eigen_vals > 0, (eigen_vals_dev - eigen_vals)/eigen_vals, 0)

#plot igraph:
#use 3 colors: red - decrease, white - no change, blue - increase
graphCol_dev = rep("white",length(rel_change))
nodes_dev <- nodes %>% mutate(rel_change = rel_change, bet= eigen_vals, betdev = eigen_vals_dev) %>% mutate(rel_color = ifelse(rel_change==0, "White", ifelse(rel_change<0, "red", "blue")))

#show which nodes changed on graph 
plot(graph_BH_dev, vertex.color=nodes_dev$rel_color, vertex.size = 5, vertex.label = NA, layout=lo)

```

```{r}
#Section 11.2 - plot relative diff of eigen vector centrality on leaflet map

# color scheme:where white  = no change, red = decrease, blue = increase 
minVal <- abs(min(rel_change))
maxVal <- abs(max(rel_change))
rc1 <- colorRampPalette(colors = c("white", "blue"), space = "Lab")(maxVal*10)
rc2 <- colorRampPalette(colors = c("red", "white"), space = "Lab")(minVal*10)
rampcols <- c(rc2, rc1)
col_pal <- colorNumeric(palette = rampcols, domain =rel_change)


m2 <- leaflet(nodes_dev) %>% addTiles() 

for(i in 1:nrow(arcs_dev)){
  node_ids <- c(arcs_dev$SOURCE_ID[i], arcs_dev$TARGET_ID[i])
  df_pol <- nodes %>% filter(DZ_Nr %in% node_ids)
  m2 <- addPolylines(m2, data = df_pol, lng = ~LON, lat = ~LAT, opacity = 0.9, group = "mylines", weight = 2) 
}
m2 <- addCircleMarkers(m2, lat = ~LAT ,lng = ~LON, weight = 1, opacity = 1, radius = 5,fillOpacity = 1, fillColor = ~col_pal(rel_change), label = ~as.character(rel_change)) %>% addLegend(position = "bottomleft", pal = col_pal, values = ~rel_change, title = as.character("Dev"),opacity = 1) 

m2 <- addCircleMarkers(m2, data = Zst_lonlats_A, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

m2 <- addCircleMarkers(m2, data = Zst_lonlats_B, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

m2

```

```{r}
#Section 11.3
#create HTML to display map 
mapshot(m2,url = paste0(getwd(), "/map_rel_diff_eigen.html"))

```

```{r}
#Section 12.0 - Closeness Centrality with deviation removed 

#Ensure correct deviation graph is used 
graph_BH_dev <- graph_from_data_frame(d = arcs_dev[,2:3], vertices = nodes_dev, directed = FALSE)

#blue = 0 closeness value, red = highest closeness value 
pal = colorRampPalette(c("blue","green",'yellow','red'))

#Line to check graph level centrality index
check <- centr_clo(graph_BH_dev)$centralization

#node level centrality score 
close_vals_dev <- centr_clo(graph_BH_dev)$res
close_vals__dev_opt2 <- closeness(
                              graph_BH_dev,
                              vids = V(graph_BH_dev),
                              mode = c("all"),
                              weights = arcs_dev$ARC_LENGTH,
                              normalized = TRUE,
                              cutoff = -1
                            )
close_vals__dev_opt3 <- harmonic_centrality(
                        graph_BH_dev,
                        vids = V(graph_BH_dev),
                        mode = c( "all"),
                        weights = arcs_dev$ARC_LENGTH,
                        normalized = FALSE,
                        cutoff = -1
                      )

graphCol_bet = pal(100)[as.numeric(cut(close_vals_dev,breaks = 100))]
graphCol_bet_opt2 = pal(100)[as.numeric(cut(close_vals__dev_opt2,breaks = 100))]
graphCol_bet_opt3 = pal(100)[as.numeric(cut(close_vals__dev_opt3,breaks = 100))]

#plot network with nodes colored based on closeness value 
plot(graph_BH_dev, vertex.color=graphCol_bet, vertex.size = 5, vertex.label = NA, layout=lo)
plot(graph_BH_dev, vertex.color=graphCol_bet_opt2, vertex.size = 5, vertex.label = NA, layout=lo)
plot(graph_BH_dev, vertex.color=graphCol_bet_opt3, vertex.size = 5, vertex.label = NA, layout=lo)



```

```{r}
#Section 12.1 - Compare Closeness centrality before and after deviation removed 

#First replace NAN values for the two nodes which are no loner connected to any other nodes with -1
close_vals_dev[is.na(close_vals_dev)] = -1

#calculate relative diff between original and modified graph 
#if closeness value org > 0 then relative diff = rel change calc
#else rel diff = 0
rel_change <- ifelse(close_vals > 0, (close_vals_dev - close_vals)/close_vals, 0)

#plot igraph:
#use 3 colors: red - decrease, white - no change, blue - increase
graphCol_dev = rep("white",length(rel_change))
nodes_dev <- nodes %>% mutate(rel_change = rel_change, bet= close_vals, betdev = close_vals_dev) %>% mutate(rel_color = ifelse(rel_change==0, "White", ifelse(rel_change<0, "red", "blue")))

#show which nodes changed on graph 
plot(graph_BH_dev, vertex.color=nodes_dev$rel_color, vertex.size = 5, vertex.label = NA, layout=lo)

```

```{r}
#Section 12.2 - plot relative diff of Closeness centrality on leaflet map

# color scheme:where white  = no change, red = decrease, blue = increase 
minVal <- abs(min(rel_change))
maxVal <- abs(max(rel_change))
rc1 <- colorRampPalette(colors = c("white", "blue"), space = "Lab")(maxVal*10)
rc2 <- colorRampPalette(colors = c("red", "white"), space = "Lab")(minVal*10)
rampcols <- c(rc2, rc1)
col_pal <- colorNumeric(palette = rampcols, domain =rel_change)


m2 <- leaflet(nodes_dev) %>% addTiles() 

for(i in 1:nrow(arcs_dev)){
  node_ids <- c(arcs_dev$SOURCE_ID[i], arcs_dev$TARGET_ID[i])
  df_pol <- nodes %>% filter(DZ_Nr %in% node_ids)
  m2 <- addPolylines(m2, data = df_pol, lng = ~LON, lat = ~LAT, opacity = 0.9, group = "mylines", weight = 2) 
}
m2 <- addCircleMarkers(m2, lat = ~LAT ,lng = ~LON, weight = 1, opacity = 1, radius = 5,fillOpacity = 1, fillColor = ~col_pal(rel_change), label = ~as.character(rel_change)) %>% addLegend(position = "bottomleft", pal = col_pal, values = ~rel_change, title = as.character("Dev"),opacity = 1) 

m2 <- addCircleMarkers(m2, data = Zst_lonlats_A, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

m2 <- addCircleMarkers(m2, data = Zst_lonlats_B, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

m2

```

```{r}
#Section 12.3
#create HTML to display map 
mapshot(m2,url = paste0(getwd(), "/map_rel_diff_close.html"))

```

```{r}

#Section 13.0  - Degree Centrality with deviation removed 

#Ensure correct deviation graph is used 
graph_BH_dev <- graph_from_data_frame(d = arcs_dev[,2:3], vertices = nodes_dev, directed = FALSE)

#blue = 0 betweenes value, red = highest betweeness value 
pal = colorRampPalette(c("blue","green",'yellow','red'))

#Use degree_betw function to determine degree centrality of our graph and save in DF
deg_vals_dev <- centr_degree(graph_BH_dev)$res

graphCol_bet = pal(100)[as.numeric(cut(deg_vals_dev,breaks = 100))]

#plot network with nodes colored based on degree value 
plot(graph_BH_dev, vertex.color=graphCol_bet, vertex.size = 5, vertex.label = NA, layout=lo)

```


```{r}

#Section 13.1 - Compare degree centrality before and after deviation removed 

#calculate relative diff between original and modified graph 
#if degree value org > 0 then relative diff = rel change calc
#else rel diff = 0
rel_change <- ifelse(deg_vals > 0, (deg_vals_dev - deg_vals)/deg_vals, 0)

#plot igraph:
#use 3 colors: red - decrease, white - no change, blue - increase
graphCol_dev = rep("white",length(rel_change))
nodes_dev <- nodes %>% mutate(rel_change = rel_change, bet= deg_vals, betdev = deg_vals_dev) %>% mutate(rel_color = ifelse(rel_change==0, "White", ifelse(rel_change<0, "red", "blue")))

#show which nodes changed on graph 
plot(graph_BH_dev, vertex.color=nodes_dev$rel_color, vertex.size = 5, vertex.label = NA, layout=lo)

```

```{r}
#Section 13.2 - plot relative diff of degree centrality on leaflet map

# color scheme:where white  = no change, red = decrease, blue = increase 
minVal <- abs(min(rel_change))
maxVal <- abs(max(rel_change))
rc1 <- colorRampPalette(colors = c("white", "blue"), space = "Lab")(.000001*10)  #(maxVal*10)
rc2 <- colorRampPalette(colors = c("red", "white"), space = "Lab")(minVal*10)
rampcols <- c(rc2, rc1)
col_pal <- colorNumeric(palette = rampcols, domain =rel_change)


m2 <- leaflet(nodes_dev) %>% addTiles() 

for(i in 1:nrow(arcs_dev)){
  node_ids <- c(arcs_dev$SOURCE_ID[i], arcs_dev$TARGET_ID[i])
  df_pol <- nodes %>% filter(DZ_Nr %in% node_ids)
  m2 <- addPolylines(m2, data = df_pol, lng = ~LON, lat = ~LAT, opacity = 0.9, group = "mylines", weight = 2) 
}
m2 <- addCircleMarkers(m2, lat = ~LAT ,lng = ~LON, weight = 1, opacity = 1, radius = 5,fillOpacity = 1, fillColor = ~col_pal(rel_change), label = ~as.character(rel_change)) %>% addLegend(position = "bottomleft", pal = col_pal, values = ~rel_change, title = as.character("Dev"),opacity = 1) 

m2 <- addCircleMarkers(m2, data = Zst_lonlats_A, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

m2 <- addCircleMarkers(m2, data = Zst_lonlats_B, lat = ~lat ,lng = ~lon ,label = ~as.character(DZ_Nr), color = "red", radius = 5, fill = FALSE)

m2

```

```{r}
#Section 13.3
#create HTML to display map 
mapshot(m2,url = paste0(getwd(), "/map_rel_diff_deg.html"))

```


```{r}
#Shortest Path Original Network - arcs not weighted

node_from <- which(nodes$DZ_Nr == 9221) #9023
node_to <- which(nodes$DZ_Nr == 9144)  #9109

path <- shortest_paths(graph_BH, from = node_from, to = node_to, output = "both")
path_vertices <- unlist(path$vpath)
path_edges <- unlist(path$epath)

graph_short <- graph_BH %>% 
  set_vertex_attr("color", index=path_vertices, value="red") %>% 
  set_edge_attr("color", value="gray") %>% 
  set_edge_attr("color", index=path_edges, value="red")  

lo <- as.matrix(nodes[,c("LON","LAT")])

plot(graph_short, vertex.size = 15, layout=lo, vertex.label.cex = 0.1)

```

```{r}
#Shortest path with arc weight - original map

node_from <- which(nodes$DZ_Nr == 9221) #9023
node_to <- which(nodes$DZ_Nr == 9144)  #9109

path_weight <- shortest_paths(graph_BH, from = node_from, to = node_to, output = "both", weights=arcs$ARC_LENGTH)
path_vertices_w <- unlist(path_weight$vpath)
path_edges_w <- unlist(path_weight$epath)

graph_short_weight <- graph_BH %>% 
  set_vertex_attr("color", index=path_vertices_w, value="green") %>% 
  set_edge_attr("color", value="gray") %>% 
  set_edge_attr("color", index=path_edges_w, value="green")

plot(graph_short_weight, vertex.size = 10, layout=lo, vertex.label.cex = 0.1)


```

```{r}
#Shortest path with arc weight in leaflet map - original map 

#color nodes and vertices of shortest path on map 
m_org <- addCircleMarkers(m_org, data = nodes %>% filter(DZ_Nr %in% names(path_vertices_w)), lat = ~LAT ,lng = ~LON , color = "mediumorchid1", radius = 3, opacity = 1, label = ~as.character(DZ_Nr), fill = FALSE)

m_org

```

```{r}
#Shortest Path Deviation Network Graph
graph_BH_dev <- graph_from_data_frame(d = arcs_dev[,2:3], vertices = nodes_dev, directed = FALSE)
```


```{r}
node_from <- which(nodes$DZ_Nr == 9221) #9023
node_to <- which(nodes$DZ_Nr == 9144)  #9109

path_dev <- shortest_paths(graph_BH_dev, from = node_from, to = node_to, output = "both")
path_vertices_dev <- unlist(path_dev$vpath)
path_edges_dev <- unlist(path_dev$epath)

graph_short_dev <- graph_BH_dev %>% 
  set_vertex_attr("color", index=path_vertices_dev, value="red") %>% 
  set_edge_attr("color", value="gray") %>% 
  set_edge_attr("color", index=path_edges_dev, value="red")  

lo <- as.matrix(nodes[,c("LON","LAT")])

plot(graph_short_dev, vertex.size = 15, layout=lo, vertex.label.cex = 0.1)
```


```{r}
#Shortest path with arc weight - deviation map

node_from <- which(nodes$DZ_Nr == 9221) #9023
node_to <- which(nodes$DZ_Nr == 9144)  #9109

path_weight_dev <- shortest_paths(graph_BH_dev, from = node_from, to = node_to, output = "both", weights=arcs_dev$ARC_LENGTH)
path_vertices_w_dev <- unlist(path_weight_dev$vpath)
path_edges_w_dev <- unlist(path_weight_dev$epath)

graph_short_dev_weight <- graph_BH_dev %>% 
  set_vertex_attr("color", index=path_vertices_w_dev, value="green") %>% 
  set_edge_attr("color", index=path_edges_w_dev, value="green")

plot(graph_short_dev_weight, vertex.size = 10, layout=lo, vertex.label.cex = 0.1)
```


```{r}
#Shortest paths with arc weight in leaflet map - deviation map + original map

#color nodes and vertices of shortest path on map 
m_dev <- addCircleMarkers(m_dev, data = nodes_dev %>% filter(DZ_Nr %in% names(path_vertices_w_dev)), lat = ~LAT ,lng = ~LON , color = "darkturquoise", radius = 3, opacity = 1, label = ~as.character(DZ_Nr), fill = FALSE) 

m_dev <- addCircleMarkers(m_dev, data = nodes %>% filter(DZ_Nr %in% names(path_vertices_w)), lat = ~LAT ,lng = ~LON , color = "yellow", radius = 3, opacity = 1, label = ~as.character(DZ_Nr), fill = FALSE) 




m_dev

#create HTML to display map 
mapshot(m_dev,url = paste0(getwd(), "/shortest_path_dev.html"))

```


